import hybridlash from "../../../assets/product/hybridlash.jpg";
import megalash from "../../../assets/product/megalash.jpg";
import classiclash from "../../../assets/product/classiclash.jpg";
import ombrebrows from "../../../assets/product/ombrebrow.jpg";
import volumelash from "../../../assets/product/volumelash.jpg";

export const products = [
  {
    _id: "001",
    name: "Hybrid Lash",
    price: "200000",
    imageurl: hybridlash,
    description: "better in all",
    quantity: 1000,
    packaging: "",
    pm: "",
    ingredient: "",
    nutritionalInfo: "",
    storage: "",
  },
  {
    _id: "001",
    name: "Classic Lash",
    price: "200000",
    imageurl: classiclash,
    description: "better in all",
    quantity: 1000,
    packaging: "",
    pm: "",
    ingredient: "",
    nutritionalInfo: "",
    storage: "",
  },
  {
    _id: "003",
    name: "Mega Lash",
    price: "200000",
    imageurl: megalash,
    description: "better in all",
    quantity: 1000,
    packaging: "",
    pm: "",
    ingredient: "",
    nutritionalInfo: "",
    storage: "",
  },
  {
    _id: "004",
    name: "Volume Lash",
    price: "200000",
    imageurl: volumelash,
    description: "better in all",
    quantity: 1000,
    packaging: "",
    pm: "",
    ingredient: "",
    nutritionalInfo: "",
    storage: "",
  },
  {
    _id: "005",
    name: "Ombre brows",
    price: "200000",
    imageurl: ombrebrows,
    description: "better in all",
    quantity: 1000,
    packaging: "",
    pm: "",
    ingredient: "",
    nutritionalInfo: "",
    storage: "",
  },
];
